version: "3.9"

services:
  weather-service:
    container_name: weather-service
    image: weather-app/weather-service:0.0.1
    environment:
      SPRING_PROFILES_ACTIVE: docker-compose
    build:
      context: ./weather_service
      dockerfile: ./Dockerfile
    ports:
      - 8528:8528

  db-mongo:
    container_name: db-mongo
    image: mongo:4.4-rc
    ports:
      - "27029:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: weather_db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    ports:
      - "8048:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: db-mongo
    depends_on:
      - db-mongo

volumes:
  mongodb_data:
